# Generated by Django 4.1 on 2022-08-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
