# Generated by Django 4.1 on 2022-08-25 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('name', models.CharField(max_length=200)),
                ('category', models.SmallIntegerField(blank=True, choices=[(0, 'Fruits'), (1, 'Vegetable'), (2, 'Fish'), (3, 'Dry Fruits'), (4, 'Egg'), (5, 'Chicken'), (6, 'Other')], null=True)),
                ('price_for_1kg', models.IntegerField()),
                ('price_for_3kg', models.IntegerField()),
                ('price_for_5kg', models.IntegerField()),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Active'), (1, 'Previous'), (2, 'Other')], null=True)),
                ('sold', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('payment_status', models.SmallIntegerField(blank=True, choices=[(0, 'Paid'), (1, 'Unpaid'), (2, 'Due')], null=True)),
                ('paid', models.IntegerField()),
                ('due', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
