# Generated by Django 4.1 on 2022-08-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'On The Way'), (1, 'Delivered'), (2, 'Cancelled')], default=0),
        ),
    ]
